### ISSUE TITLE
Add sass-lang in vuetify boilerplate

### ISSUE THREAD

**Issue by singgihsap** [agallio/nuxtku#13]
**Is your feature request related to a problem? Please describe.**
Add sass-lang to the vuetify boilerplate for easy write css structured and for maintenance development.

**Describe the solution you'd like**
Add scss (sass-lang) to the vuetify boilerplate.

**Describe alternatives you've considered**
_None_

**Additional context**
_None_

**Comment by agallio** [comment]
@singgihsap

Same like the #12 issue, I can't do this right now because I have other needs. If you can, please create a pull request for this issue. Thank you 👍
