### ISSUE TITLE
Add Bootstrap boilerplate

### ISSUE THREAD

**Issue by singgihsap** [agallio/nuxtku#4]
**Is your feature request related to a problem? Please describe.**
Bootstrap vue is the most used css framework in our Nuxt projects.

**Describe the solution you'd like**
Add plain Bootstrap vue boilerplate without OAuth and/or other modules is OK.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by agallio** [comment]
Hmmm, interesting. Could you make a pull request for the bootstrap boilerplate? @singgihsap

**Comment by agallio** [comment]
Invite sent to your email! Please kindly check your email. @singgihsap

**Comment by singgihsap** [comment]
Thank you @agallio
